### ISSUE TITLE
Facebook Permissions

### ISSUE THREAD

**Issue by mitch82** [ThinkUpLLC/ThinkUp#2246]
As commented in issue  #1848 the instructions to add a facebook app have to be changed.  Following those instructions, i was unable to log into and add a facebook account to thinkup.

![fb_permissions](https://cloud.githubusercontent.com/assets/12587096/7789091/3119da96-024c-11e5-80b6-57249285d0bc.JPG)

Has anyone come across such a problem before?

**Comment by oleonard** [comment]
I got an identical error today using a brand-new installation of 2.0-beta.10.

**Comment by ginatrapani** [comment]
Sorry the last release is out of date; this has been fixed in the master branch (and will be in the next user release).

**Comment by ramielbarsoum** [comment]
Has this been corrected? i have installed using the master branch and this error still exists in this release.

**Comment by ginatrapani** [comment]
I believe it has been corrected in the current state of the master branch. You can see here:

https://github.com/ThinkUpLLC/ThinkUp/blob/master/webapp/plugins/facebook/controller/class.FacebookPluginConfigurationController.php#L112

The scope is set to user_posts,email.

**Comment by ramielbarsoum** [comment]
@ginatrapani thank you for your reply
Is the master branch and the download files not up to date with each other?

**Comment by ginatrapani** [comment]
No, they aren't, sorry.
